### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DSLZL** [LOOHP/LotterySix#4]
`[11:40:28 ERROR]: Error occurred while enabling LotterySix v1.10.11.0 (Is it up to date?)
com.loohp.lotterysix.libs.com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 367 column 1 path $[40].gameNumber
.
        at com.loohp.lotterysix.libs.com.google.gson.Gson.fromJson(Gson.java:1068) ~[LotterySix-1.10.11.0.jar:?]
        at com.loohp.lotterysix.libs.com.google.gson.Gson.fromJson(Gson.java:986) ~[LotterySix-1.10.11.0.jar:?]
        at com.loohp.lotterysix.game.LotterySix.loadData(LotterySix.java:1094) ~[LotterySix-1.10.11.0.jar:?]
        at com.loohp.lotterysix.game.LotterySix.<init>(LotterySix.java:396) ~[LotterySix-1.10.11.0.jar:?]
        at com.loohp.lotterysix.LotterySixPlugin.onEnable(LotterySixPlugin.java:133) ~[LotterySix-1.10.11.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:g
it-Paper-"850b736"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper
-"850b736"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-"850b736"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-"850b736"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-"850b736"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-"850b736"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-"850b736"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-"850b736"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-"850b736"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.io.EOFException: End of input at line 367 column 1 path $[40].gameNumber.
        at com.loohp.lotterysix.libs.com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1406) ~[LotterySix-1.10.11.0.jar:?]
        at com.loohp.lotterysix.libs.com.google.gson.stream.JsonReader.doPeek(JsonReader.java:504) ~[LotterySix-1.10.11.0.jar:?]
        at com.loohp.lotterysix.libs.com.google.gson.stream.JsonReader.hasNext(JsonReader.java:424) ~[LotterySix-1.10.11.0.jar:?]
        at com.loohp.lotterysix.libs.com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:752) ~[LotterySix-1.10.11.0.jar:?]
        at com.loohp.lotterysix.libs.com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:698) ~[LotterySix-1.10.11.0.jar:?]
        at com.loohp.lotterysix.libs.com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:979) ~[LotterySix-1.10.11.0.jar:
?]
        at com.loohp.lotterysix.libs.com.google.gson.Gson.fromJson(Gson.java:1058) ~[LotterySix-1.10.11.0.jar:?]
        ... 16 more
[11:40:28 INFO]: [LotterySix] Disabling LotterySix v1.10.11.0
[11:40:28 ERROR]: Error occurred while disabling LotterySix v1.10.11.0
java.lang.NullPointerException: Cannot invoke "com.loohp.lotterysix.game.LotterySix.close()" because "com.loohp.lotterysix.LotterySixPlugin.
instance" is null
        at com.loohp.lotterysix.LotterySixPlugin.onDisable(LotterySixPlugin.java:248) ~[LotterySix-1.10.11.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:223) ~[paper-1.20.4.jar:
git-Paper-"850b736"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.4.jar:git-Pape
r-"850b736"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.20.4.jar:g
it-Paper-"850b736"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper
-"850b736"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-"850b736"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-"850b736"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-"850b736"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-"850b736"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-"850b736"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-"850b736"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-"850b736"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by LOOHP** [comment]
Try clearing all the past games data in the plugin folder and then restart.

**Comment by DSLZL** [comment]
Thanks.
