### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by gamminglord2012** [LOOHP/LotterySix#7]
my logs tell me this 
[16:17:18 ERROR]: [ModernPluginLoadingStrategy] Could not load 'plugins/.paper-remapped/LotterySix-1.10.13.0.jar' in 'plugins/.paper-remapped'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [PlaceholderAPI]. Please download and install these plugins to run 'LotterySix'.
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:82) ~[paper-1.21.jar:1.21-37-dd49fba]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.21.jar:1.21-37-dd49fba]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.jar:1.21-37-dd49fba]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:535) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:290) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-37-dd49fba]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by LOOHP** [comment]
Unknown/missing dependency plugins: [PlaceholderAPI]. Please download and install these plugins to run 'LotterySix'.

**Comment by gamminglord2012** [comment]
Thx

**Comment by gamminglord2012** [comment]
still is refusing to work

**Comment by LOOHP** [comment]
Please look for errors in the console.

**Comment by gamminglord2012** [comment]
Same error

**Comment by LOOHP** [comment]
It probably isn't, can you show the new error?

**Comment by gamminglord2012** [comment]
[ModernPluginLoadingStrategy] Could not load 'plugins/.paper-remapped/LotterySix-1.10.13.0.jar' in 'plugins/.paper-remapped'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [PlaceholderAPI]. Please download and install these plugins to run 'LotterySix'.
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:82) ~[paper-1.21.jar:1.21-47-62ed302]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.21.jar:1.21-47-62ed302]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.jar:1.21-47-62ed302]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:535) ~[paper-1.21.jar:1.21-47-62ed302]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:290) ~[paper-1.21.jar:1.21-47-62ed302]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1219) ~[paper-1.21.jar:1.21-47-62ed302]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-47-62ed302]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by gamminglord2012** [comment]
If its the api is not right can you send me the right one

**Comment by LOOHP** [comment]
Are you sure you really installed PlaceholderAPI?

**Comment by gamminglord2012** [comment]
Idk the provider i normly use banned my ip for some reson

**Comment by gamminglord2012** [comment]
So i dont know how to find one if that dous not work

**Comment by LOOHP** [comment]
Are you able to download PAPI from SpigotMC?

**Comment by gamminglord2012** [comment]
No thats what i got banned from

**Comment by LOOHP** [comment]
What about on their [Github](https://github.com/PlaceholderAPI/PlaceholderAPI)?

**Comment by gamminglord2012** [comment]
Idk how Just know how to comment

**Comment by gamminglord2012** [comment]
Can you get on modrinth

**Comment by LOOHP** [comment]
On [hangar](https://hangar.papermc.io/HelpChat/PlaceholderAPI)?

**Comment by gamminglord2012** [comment]
Whats hanger

**Comment by LOOHP** [comment]
It still works.

**Comment by gamminglord2012** [comment]
Thx

**Comment by gamminglord2012** [comment]
Still not working

**Comment by gamminglord2012** [comment]
Can my plugins cancel it

**Comment by gamminglord2012** [comment]
Do i need to chage some of the plugins code for some u haft to do that?
