### ISSUE TITLE
still no work

### ISSUE THREAD

**Issue by gamminglord2012** [LOOHP/LotterySix#8]
it stll tells me this [08:43:29 ERROR]: [ModernPluginLoadingStrategy] Could not load 'plugins/.paper-remapped/LotterySix-1.10.13.0.jar' in 'plugins/.paper-remapped'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [PlaceholderAPI]. Please download and install these plugins to run 'LotterySix'.
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:82) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:535) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:290) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
[08:43:30 ERROR]: [ModernPluginLoadingStrategy] Could not load 'plugins/.paper-remapped/AxRankMenu-1.6.0.jar' in 'plugins/.paper-remapped'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [LuckPerms]. Please download and install these plugins to run 'AxRankMenu'.
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:82) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:535) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:290) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
[08:43:30 ERROR]: [ModernPluginLoadingStrategy] Could not load 'plugins/PlaceholderAPI-Expansion-1.2.0.jar' in 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [MiniPlaceholders, PlaceholderAPI]. Please download and install these plugins to run 'PlaceholderAPI-Expansion'.
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:82) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:535) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:290) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by ipaulocesar** [comment]
![image](https://github.com/user-attachments/assets/90aa7352-e2e8-4ed0-a348-858ab39f91ab)

[https://www.spigotmc.org/resources/vault.34315/](url)
[https://www.spigotmc.org/resources/essentialsx.9089/](url)
[https://www.spigotmc.org/resources/placeholderapi.6245/](url)
